# Generated by AI (UnitTest MCP)
"""Team-shaped Horizon intake through Dream's delegated port."""

from __future__ import annotations

from dream.contracts import (
    DelegatedWorkRef,
    DelegatedWorkRequest,
    StaffingBlocked,
    StaffingRequirement,
)

from horizon.intake import DelegatedSubmitter
from horizon.model import Goal, StrategyRecord
from horizon.store import StrategyStore


class FakeDelegatedIntake:
    def __init__(self, result: DelegatedWorkRef | StaffingBlocked) -> None:
        self.result = result
        self.requests: list[DelegatedWorkRequest] = []

    def submit_delegated(self, request: DelegatedWorkRequest) -> DelegatedWorkRef | StaffingBlocked:
        self.requests.append(request)
        return self.result


def _team_goal() -> Goal:
    return Goal(
        id="goal-1",
        title="Ship coordinated launch",
        score=0.9,
        delivery_shape="team",
        lead_professions=("pm",),
        staffing_requirements=(
            StaffingRequirement(profession="engineer", count=2),
            StaffingRequirement(profession="designer"),
        ),
    )


def test_delegated_submitter_records_request_and_durable_identities(tmp_path) -> None:
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            title="Ship coordinated launch",
            score=0.9,
            delivery_shape="team",
            lead_professions=_team_goal().lead_professions,
            staffing_requirements=_team_goal().staffing_requirements,
        )
    )
    port = FakeDelegatedIntake(
        DelegatedWorkRef(root_task_id="root-1", team_id="team-1", lead_id="lead-1")
    )

    result = DelegatedSubmitter(intake=port, strategy=strategy).submit(_team_goal())
    record = strategy.get("goal-1")

    assert result == DelegatedWorkRef("root-1", "team-1", "lead-1")
    assert port.requests == [
        DelegatedWorkRequest(
            intent="Ship coordinated launch",
            goal_id="goal-1",
            priority="high",
            requirements=_team_goal().staffing_requirements,
            lead_professions=_team_goal().lead_professions,
            origin_fingerprint=port.requests[0].origin_fingerprint,
        )
    ]
    assert record is not None and (
        record.root_task_id,
        record.task_id,
        record.task_ids,
        record.team_id,
        record.lead_id,
        record.attempts,
    ) == ("root-1", "root-1", ["root-1"], "team-1", "lead-1", 1)


def test_delegated_submitter_is_idempotent_before_port_call(tmp_path) -> None:
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            root_task_id="root-1",
            team_id="team-1",
            lead_id="lead-1",
            delivery_shape="team",
        )
    )
    port = FakeDelegatedIntake(StaffingBlocked(goal_id="goal-1", reason="should not run"))

    result = DelegatedSubmitter(intake=port, strategy=strategy).submit(_team_goal())

    assert result == DelegatedWorkRef("root-1", "team-1", "lead-1")
    assert port.requests == []


def test_delegated_submitter_preserves_typed_staffing_failure_without_mutation(tmp_path) -> None:
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            score=0.9,
            delivery_shape="team",
            staffing_requirements=_team_goal().staffing_requirements,
        )
    )
    blocked = StaffingBlocked(goal_id="goal-1", reason="no eligible lead")
    port = FakeDelegatedIntake(blocked)

    result = DelegatedSubmitter(intake=port, strategy=strategy).submit(_team_goal())
    record = strategy.get("goal-1")

    assert result == blocked
    assert record is not None and (
        record.root_task_id,
        record.team_id,
        record.lead_id,
        record.attempts,
    ) == (None, None, None, 0)
