"""Slice 3 (feedback): the OutcomeListener folds landed verdicts into health + re-priority."""

# Generated by AI (UnitTest MCP)

from __future__ import annotations

from horizon.feedback import OutcomeListener
from horizon.intake import Prioritiser
from horizon.model._strategy import StrategyRecord
from horizon.ports import OutcomeEvent
from horizon.store import StrategyStore
from tests.fakes import FakeIntakePort, FakeOutcomeFeed


def _wire(tmp_path, record):
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(record)
    feed = FakeOutcomeFeed()
    intake = FakeIntakePort()
    listener = OutcomeListener(outcomes=feed, strategy=strategy, prioritiser=Prioritiser(intake))
    return listener, feed, strategy, intake


def test_pass_verdict_updates_health_and_reprioritises(tmp_path):
    listener, feed, strategy, intake = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()

    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))

    updated = strategy.get("g1")
    assert updated.health == "on_track"
    assert updated.score == 0.4
    assert intake.priorities["task_1"] == "medium"  # 0.4 -> medium
    assert listener.handled == 1


def test_fail_verdict_bumps_score_and_reprioritises(tmp_path):
    listener, feed, strategy, intake = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.6, task_id="task_1")
    )
    listener.start()

    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=False))

    updated = strategy.get("g1")
    assert updated.health == "blocked"  # no prior pass
    assert updated.score == 0.85  # 0.6 + 0.25
    assert intake.priorities["task_1"] == "high"


def test_non_verdict_events_are_ignored(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()

    feed.emit(OutcomeEvent(kind="run.done", task_id="task_1", goal_id="g1", passed=True))
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=None))

    assert strategy.get("g1").health == "unknown"
    assert listener.handled == 0


def test_outcome_for_unknown_goal_is_ignored(tmp_path):
    listener, feed, _, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()

    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_x", goal_id="other", passed=True))

    assert listener.handled == 0


def test_stop_unsubscribes(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()
    listener.stop()

    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))

    assert listener.handled == 0
    assert strategy.get("g1").health == "unknown"


def test_counters_classify_every_event(tmp_path):
    listener, feed, _, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()

    # non-outcome kinds -> ignored silently (no counter moves)
    feed.emit(OutcomeEvent(kind="run.tool_use", task_id="task_1", goal_id="g1"))
    feed.emit(OutcomeEvent(kind="run.done", task_id="task_1", goal_id="g1"))
    # verdict-kind but no pass/fail yet (needs-changes) -> deferred
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=None))
    # a verdict for a goal horizon does not own -> dropped
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="tX", goal_id="other", passed=True))
    # a real verdict -> handled
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))

    assert (listener.handled, listener.dropped, listener.deferred) == (1, 1, 1)


def test_pass_marks_goal_done(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.8, task_id="task_1")
    )
    listener.start()
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))
    assert strategy.get("g1").done is True


def test_fail_does_not_mark_done(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.6, task_id="task_1")
    )
    listener.start()
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=False))
    assert strategy.get("g1").done is False


def test_fail_flags_recovery_and_stores_diagnostic(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.6, task_id="task_1")
    )
    listener.start()
    feed.emit(
        OutcomeEvent(
            kind="run.evaluated",
            task_id="task_1",
            goal_id="g1",
            passed=False,
            detail="evaluator reply missing <verdict> section",
        )
    )
    record = strategy.get("g1")
    assert record.needs_recovery is True
    assert "missing <verdict>" in record.last_diagnostic


def test_pass_clears_recovery_flag_and_diagnostic(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path,
        StrategyRecord(
            goal_id="g1", score=0.6, task_id="task_1", needs_recovery=True, last_diagnostic="old"
        ),
    )
    listener.start()
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))
    record = strategy.get("g1")
    assert record.needs_recovery is False
    assert record.last_diagnostic == ""
    assert record.done is True


def test_listener_survives_a_realistic_noisy_stream(tmp_path):
    # A whole beat's event stream: telemetry noise + a needs-changes sprint + a fail + a final pass.
    listener, feed, strategy, _ = _wire(
        tmp_path, StrategyRecord(goal_id="g1", score=0.7, task_id="task_1")
    )
    listener.start()

    for kind in ("run.started", "run.text", "run.tool_use", "run.tool_result", "run.text"):
        feed.emit(OutcomeEvent(kind=kind, task_id="task_1", goal_id="g1"))
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=None))
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=False))
    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="task_1", goal_id="g1", passed=True))
    feed.emit(OutcomeEvent(kind="run.done", task_id="task_1", goal_id="g1"))

    record = strategy.get("g1")
    assert (record.passes, record.fails) == (1, 1)
    assert record.health == "on_track"  # converged: the final verdict was a pass
    assert record.done is True
    # counters account for every event: 2 verdicts folded, 1 needs-changes deferred, noise ignored
    assert (listener.handled, listener.deferred, listener.dropped) == (2, 1, 0)


def test_team_child_pass_is_evidence_but_does_not_finish_goal(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path,
        StrategyRecord(
            goal_id="g1",
            score=0.8,
            root_task_id="root-1",
            delivery_shape="team",
        ),
    )
    listener.start()

    feed.emit(OutcomeEvent(kind="run.evaluated", task_id="child-1", goal_id="g1", passed=True))

    record = strategy.get("g1")
    assert record.done is False
    assert record.task_outcomes == {"child-1": "passed"}


def test_team_blocked_child_status_blocks_goal(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path,
        StrategyRecord(
            goal_id="g1",
            score=0.8,
            root_task_id="root-1",
            delivery_shape="team",
        ),
    )
    listener.start()

    feed.emit(
        OutcomeEvent(
            kind="task.status",
            task_id="child-1",
            goal_id="g1",
            status="blocked",
        )
    )

    record = strategy.get("g1")
    assert record.health == "blocked"
    assert record.task_outcomes == {"child-1": "blocked"}


def test_duplicate_team_verdict_is_not_counted_or_prioritised_twice(tmp_path):
    listener, feed, strategy, _ = _wire(
        tmp_path,
        StrategyRecord(
            goal_id="g1",
            score=0.2,
            root_task_id="root-1",
            delivery_shape="team",
        ),
    )
    listener.start()
    event = OutcomeEvent(kind="run.evaluated", task_id="child-1", goal_id="g1", passed=False)

    feed.emit(event)
    feed.emit(event)

    record = strategy.get("g1")
    assert (record.fails, record.score, listener.handled) == (1, 0.45, 1)
