"""B3 effective priority keeps strategic value separate from execution pressure."""

# Generated by AI (UnitTest MCP)

from __future__ import annotations

import pytest

from horizon.planning import EffectivePriorityPolicy
from horizon.ports import ProfessionCapacity, StaffingRequirement


def _capacity(
    *,
    profession: str = "engineer",
    eligible: int = 2,
    running: int = 0,
    assigned: int = 0,
    wakes: int = 0,
    budget_blocked: int = 0,
    headroom: int | None = 10_000,
) -> ProfessionCapacity:
    return ProfessionCapacity(
        profession=profession,
        eligible=eligible,
        running=running,
        assigned_nonterminal=assigned,
        queued_wakes=wakes,
        budget_blocked=budget_blocked,
        budget_headroom_cents=headroom,
    )


def test_missing_required_capacity_is_visibly_staffing_blocked():
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.86,
        requirements=(StaffingRequirement("engineer"),),
        capacities=(_capacity(eligible=0),),
    )

    assert result.score == 0.0
    assert result.priority == "staffing_blocked"
    assert "engineer" in result.reason


def test_low_load_preserves_raw_score_and_priority():
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.8,
        requirements=(StaffingRequirement("engineer"),),
        capacities=(_capacity(eligible=4, running=1),),
    )

    assert (result.score, result.priority) == (0.8, "high")
    assert "load" in result.reason


def test_heavy_load_dampens_effective_score():
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.8,
        requirements=(StaffingRequirement("engineer"),),
        capacities=(_capacity(eligible=1, running=1, assigned=1, wakes=1),),
    )

    assert (result.score, result.priority) == (0.4, "medium")
    assert "heavy" in result.reason


def test_fully_budget_blocked_capacity_is_surfaced():
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.9,
        requirements=(StaffingRequirement("engineer", count=2),),
        capacities=(_capacity(eligible=2, budget_blocked=2, headroom=0),),
    )

    assert result.priority == "staffing_blocked"
    assert "budget" in result.reason


def test_unready_dependencies_dampen_but_do_not_mutate_raw_value():
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.8,
        requirements=(StaffingRequirement("engineer"),),
        capacities=(_capacity(eligible=4),),
        dependencies_ready=False,
    )

    assert (result.score, result.priority) == (0.4, "medium")
    assert "dependenc" in result.reason


def test_load_weights_are_configurable_policy_data():
    policy = EffectivePriorityPolicy(load_bands=((float("inf"), 0.25, "constrained"),))

    result = policy.evaluate(
        raw_score=0.8,
        requirements=(StaffingRequirement("engineer"),),
        capacities=(_capacity(),),
    )

    assert result.score == 0.2
    assert "constrained" in result.reason


@pytest.mark.parametrize(
    "requirements, capacities",
    [
        ((), ()),
        ((StaffingRequirement("engineer"),), (_capacity(),)),
        ((StaffingRequirement("designer"),), (_capacity(),)),
    ],
)
def test_every_result_has_a_reason(requirements, capacities):
    result = EffectivePriorityPolicy().evaluate(
        raw_score=0.5,
        requirements=requirements,
        capacities=capacities,
    )

    assert result.reason.strip()