# Generated by AI (UnitTest MCP)
"""Execution-shape persistence for single and delegated goals."""

from __future__ import annotations

import json

from dream.contracts import StaffingRequirement

from horizon.model import Goal
from horizon.model._strategy import StrategyRecord
from horizon.store import StrategyStore


def test_strategy_record_defaults_preserve_single_task_behavior() -> None:
    record = StrategyRecord(goal_id="goal-1", task_id="task-1")

    assert (
        record.delivery_shape,
        record.staffing_requirements,
        record.root_task_id,
        record.task_id,
        record.task_ids,
        record.team_id,
        record.lead_id,
        record.task_outcomes,
    ) == ("single", (), "task-1", "task-1", [], None, None, {})


def test_strategy_store_loads_legacy_json_without_execution_shape(tmp_path) -> None:
    path = tmp_path / "strategy.json"
    path.write_text(
        json.dumps({"goal-1": {"goal_id": "goal-1", "task_id": "task-1", "score": 0.7}}),
        encoding="utf-8",
    )

    record = StrategyStore(path).get("goal-1")

    assert record is not None and (record.root_task_id, record.task_id) == ("task-1", "task-1")


def test_strategy_store_round_trips_typed_team_execution_shape(tmp_path) -> None:
    store = StrategyStore(tmp_path / "strategy.json")
    store.put(
        StrategyRecord(
            goal_id="goal-1",
            task_id="legacy-task",
            root_task_id="root-task",
            task_ids=["root-task", "child-task"],
            team_id="team-1",
            lead_id="lead-1",
            task_outcomes={"child-task": "passed"},
            delivery_shape="team",
            staffing_requirements=(
                StaffingRequirement(profession="engineer", count=2),
                StaffingRequirement(profession="designer"),
            ),
        )
    )

    restored = store.get("goal-1")

    # Both identities survive as written: backfill only fills a MISSING side, never overwrites a
    # set one — recover() legitimately points task_id at a new retry task (and moves the root too).
    assert restored is not None and (
        restored.task_id,
        restored.root_task_id,
        restored.staffing_requirements,
    ) == (
        "legacy-task",
        "root-task",
        (
            StaffingRequirement(profession="engineer", count=2),
            StaffingRequirement(profession="designer"),
        ),
    )


def test_goal_defaults_to_single_execution_without_staffing() -> None:
    goal = Goal(id="goal-1", title="Ship it")

    assert (goal.delivery_shape, goal.staffing_requirements) == ("single", ())
