"""Slice 3 (facade): the Horizon facade composes the full loop over fakes."""

# Generated by AI (UnitTest MCP)

from __future__ import annotations

import json

import pytest
from dream.contracts import (
    DelegatedWorkRef,
    DelegatedWorkRequest,
    GoalNode,
    ProfessionCapacity,
    StaffingBlocked,
    StaffingRequirement,
)

from horizon import Horizon
from horizon.errors import HorizonError
from horizon.model import Decision, Goal, StrategyRecord
from horizon.ports import OutcomeEvent
from horizon.store import DecisionStore, StrategyStore
from tests.fakes import FakeGoalStore, FakeIntakePort, FakeOutcomeFeed, FakeSubstrate


class _DelegatedIntake:
    def __init__(self, result: DelegatedWorkRef | StaffingBlocked) -> None:
        self.result = result
        self.requests: list[DelegatedWorkRequest] = []

    def submit_delegated(self, request: DelegatedWorkRequest) -> DelegatedWorkRef | StaffingBlocked:
        self.requests.append(request)
        return self.result


class _Capacity:
    def snapshot(self) -> tuple[ProfessionCapacity, ...]:
        return (
            ProfessionCapacity(
                profession="engineer",
                eligible=1,
                running=1,
                assigned_nonterminal=1,
                queued_wakes=1,
                budget_blocked=0,
                budget_headroom_cents=10_000,
            ),
        )


def _horizon(tmp_path, substrate_text):
    goals = FakeGoalStore()
    intake = FakeIntakePort()
    feed = FakeOutcomeFeed()
    horizon = Horizon(
        goals=goals,
        intake=intake,
        outcomes=feed,
        reasoner=FakeSubstrate(substrate_text),
        decisions=DecisionStore(tmp_path / "decisions.json"),
        strategy=StrategyStore(tmp_path / "strategy.json"),
        default_assignee="moe",
    )
    return horizon, goals, intake, feed


def test_full_loop_seed_decompose_submit_state(tmp_path):
    text = json.dumps(
        {"goals": [{"title": "Build API", "score": 0.9}, {"title": "Build UI", "score": 0.5}]}
    )
    horizon, _, intake, _ = _horizon(tmp_path, text)
    horizon.seed_decision(Decision(id="dec_1", statement="Build an AI note-taker", owner="moe"))

    made = horizon.decompose("dec_1")
    assert len(made) == 2

    task_ids = horizon.submit_decision("dec_1")
    assert len(task_ids) == 2
    assert len(intake.submitted) == 2

    states = horizon.state()
    assert len(states) == 1
    view = states[0]
    assert view.decision.id == "dec_1"
    assert {g.title for g in view.goals} == {"Build API", "Build UI"}
    assert all(g.task_id is not None and g.owner == "moe" for g in view.goals)

    priorities = {g.title: intake.priorities[g.task_id] for g in view.goals}
    assert priorities["Build API"] == "high"  # score 0.9
    assert priorities["Build UI"] == "medium"  # score 0.5


def test_submit_decision_is_idempotent(tmp_path):
    text = json.dumps({"goals": [{"title": "Build API", "score": 0.9}]})
    horizon, _, intake, _ = _horizon(tmp_path, text)
    horizon.seed_decision(Decision(id="dec_1", statement="x", owner="moe"))
    horizon.decompose("dec_1")

    first = horizon.submit_decision("dec_1")
    second = horizon.submit_decision("dec_1")
    assert first == second
    assert len(intake.submitted) == 1


def test_facade_routes_team_goal_through_delegated_intake(tmp_path):
    strategy = StrategyStore(tmp_path / "strategy.json")
    requirements = (StaffingRequirement(profession="engineer", count=2),)
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            score=0.9,
            delivery_shape="team",
            staffing_requirements=requirements,
        )
    )
    delegated = _DelegatedIntake(DelegatedWorkRef("root-1", "team-1", "lead-1"))
    horizon = Horizon(
        goals=FakeGoalStore(),
        intake=FakeIntakePort(),
        delegated_intake=delegated,
        outcomes=FakeOutcomeFeed(),
        strategy=strategy,
        decisions=DecisionStore(tmp_path / "decisions.json"),
    )

    result = horizon.submit_goal(
        Goal(
            id="goal-1",
            title="Ship coordinated launch",
            delivery_shape="team",
            staffing_requirements=requirements,
        )
    )

    assert result == "root-1"
    assert delegated.requests[0].requirements == requirements


def test_submit_decision_preserves_team_shape_from_strategy_record(tmp_path):
    goals = FakeGoalStore()
    goals.upsert(GoalNode(id="goal-1", title="Ship launch", level="goal"))
    decisions = DecisionStore(tmp_path / "decisions.json")
    decisions.put(Decision(id="dec-1", statement="Launch", goal_ids=["goal-1"]))
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            delivery_shape="team",
            staffing_requirements=(StaffingRequirement(profession="engineer"),),
        )
    )
    delegated = _DelegatedIntake(DelegatedWorkRef("root-1", "team-1", "lead-1"))
    horizon = Horizon(
        goals=goals,
        intake=FakeIntakePort(),
        delegated_intake=delegated,
        outcomes=FakeOutcomeFeed(),
        strategy=strategy,
        decisions=decisions,
    )

    results = horizon.submit_decision("dec-1")

    assert results == ["root-1"] and len(delegated.requests) == 1


def test_facade_returns_typed_staffing_block(tmp_path):
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(StrategyRecord(goal_id="goal-1", delivery_shape="team"))
    blocked = StaffingBlocked(goal_id="goal-1", reason="no eligible lead")
    horizon = Horizon(
        goals=FakeGoalStore(),
        intake=FakeIntakePort(),
        delegated_intake=_DelegatedIntake(blocked),
        outcomes=FakeOutcomeFeed(),
        strategy=strategy,
        decisions=DecisionStore(tmp_path / "decisions.json"),
    )

    result = horizon.submit_goal(Goal(id="goal-1", title="Ship", delivery_shape="team"))

    assert result == blocked


def test_facade_refuses_team_goal_without_delegated_port(tmp_path):
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(StrategyRecord(goal_id="goal-1", delivery_shape="team"))
    horizon = Horizon(
        goals=FakeGoalStore(),
        intake=FakeIntakePort(),
        outcomes=FakeOutcomeFeed(),
        strategy=strategy,
        decisions=DecisionStore(tmp_path / "decisions.json"),
    )

    with pytest.raises(HorizonError, match="delegated intake"):
        horizon.submit_goal(Goal(id="goal-1", title="Ship", delivery_shape="team"))


def test_goal_view_projects_team_execution_and_effective_priority(tmp_path):
    goals = FakeGoalStore()
    goals.upsert(GoalNode(id="goal-1", title="Ship launch", level="goal"))
    strategy = StrategyStore(tmp_path / "strategy.json")
    strategy.put(
        StrategyRecord(
            goal_id="goal-1",
            score=0.8,
            root_task_id="root-1",
            task_ids=["root-1", "child-1"],
            team_id="team-1",
            lead_id="lead-1",
            task_outcomes={"child-1": "passed"},
            delivery_shape="team",
            staffing_requirements=(StaffingRequirement("engineer"),),
        )
    )
    horizon = Horizon(
        goals=goals,
        intake=FakeIntakePort(),
        outcomes=FakeOutcomeFeed(),
        capacity=_Capacity(),
        strategy=strategy,
        decisions=DecisionStore(tmp_path / "decisions.json"),
    )

    goal = horizon.goal_view("goal-1")

    assert goal is not None
    assert (goal.root_task_id, goal.task_ids) == ("root-1", ["root-1", "child-1"])
    assert (goal.team_id, goal.lead_id) == ("team-1", "lead-1")
    assert goal.task_outcomes == {"child-1": "passed"}
    assert (goal.effective_score, goal.effective_priority) == (0.4, "medium")
    assert "heavy" in goal.priority_reason


def test_start_then_failed_outcome_updates_state_and_priority(tmp_path):
    text = json.dumps({"goals": [{"title": "Build API", "score": 0.9}]})
    horizon, _, intake, feed = _horizon(tmp_path, text)
    horizon.seed_decision(Decision(id="dec_1", statement="x", owner="moe"))
    horizon.decompose("dec_1")
    horizon.submit_decision("dec_1")
    horizon.start()

    goal = horizon.state()[0].goals[0]
    feed.emit(
        OutcomeEvent(kind="run.evaluated", task_id=goal.task_id, goal_id=goal.id, passed=False)
    )

    after = horizon.state()[0].goals[0]
    assert after.health == "blocked"
    assert after.score == 1.0  # 0.9 + 0.25 -> clamp
    assert intake.priorities[goal.task_id] == "high"


def test_passing_outcome_marks_goal_done_in_state(tmp_path):
    text = json.dumps({"goals": [{"title": "Build API", "score": 0.9}]})
    horizon, _, _, feed = _horizon(tmp_path, text)
    horizon.seed_decision(Decision(id="dec_1", statement="x", owner="moe"))
    horizon.decompose("dec_1")
    horizon.submit_decision("dec_1")
    horizon.start()

    goal = horizon.state()[0].goals[0]
    feed.emit(
        OutcomeEvent(kind="run.evaluated", task_id=goal.task_id, goal_id=goal.id, passed=True)
    )

    assert horizon.state()[0].goals[0].status == "done"
    assert horizon.listener_stats() == {"handled": 1, "dropped": 0, "deferred": 0}


def test_decompose_without_reasoner_raises(tmp_path):
    horizon = Horizon(
        goals=FakeGoalStore(),
        intake=FakeIntakePort(),
        outcomes=FakeOutcomeFeed(),
        decisions=DecisionStore(tmp_path / "decisions.json"),
        strategy=StrategyStore(tmp_path / "strategy.json"),
    )
    horizon.seed_decision(Decision(id="dec_1", statement="x"))
    with pytest.raises(HorizonError):
        horizon.decompose("dec_1")


def _decomposed_horizon(tmp_path):
    text = json.dumps({"goals": [{"title": "Build API", "score": 0.9}]})
    horizon, _, intake, feed = _horizon(tmp_path, text)
    horizon.seed_decision(Decision(id="dec_1", statement="x", owner="moe"))
    horizon.decompose("dec_1")
    horizon.submit_decision("dec_1")
    horizon.start()
    return horizon, intake, feed


def test_recover_resubmits_failed_goal_with_diagnostic(tmp_path):
    horizon, intake, feed = _decomposed_horizon(tmp_path)
    goal = horizon.state()[0].goals[0]

    feed.emit(
        OutcomeEvent(
            kind="run.evaluated",
            task_id=goal.task_id,
            goal_id=goal.id,
            passed=False,
            detail="evaluator reply missing <verdict> section",
        )
    )

    recovered = horizon.recover(max_attempts=3)
    assert recovered == [goal.id]
    assert len(intake.submitted) == 2  # original + one recovery
    retry = intake.submitted[-1]
    assert "missing <verdict>" in retry["intent"]
    assert "previous attempt" in retry["intent"].lower()
    assert retry["fingerprint"] != intake.submitted[0]["fingerprint"]  # a fresh task, not a dedup

    assert horizon.recover() == []  # needs_recovery cleared -> no-op


def test_recover_respects_max_attempts(tmp_path):
    horizon, intake, feed = _decomposed_horizon(tmp_path)

    for _ in range(5):
        goal = horizon.state()[0].goals[0]
        feed.emit(
            OutcomeEvent(
                kind="run.evaluated",
                task_id=goal.task_id,
                goal_id=goal.id,
                passed=False,
                detail="nope",
            )
        )
        horizon.recover(max_attempts=2)

    # initial submit (attempt 1) + exactly one recovery (attempt 2) — then capped
    assert len(intake.submitted) == 2


def test_note_outcome_funnels_a_consumer_detected_failure(tmp_path):
    horizon, intake, _ = _decomposed_horizon(tmp_path)
    goal = horizon.state()[0].goals[0]

    # a beat that errored (no bus verdict) — the composition root reports it
    horizon.note_outcome(
        goal.id, passed=False, diagnostic="RunTaskError: evaluator reply missing <verdict>"
    )
    assert horizon.listener_stats()["handled"] == 1

    recovered = horizon.recover()
    assert recovered == [goal.id]
    assert "evaluator reply missing <verdict>" in intake.submitted[-1]["intent"]


def test_sweep_staleness_drifts_and_resurfaces_aged_goals(tmp_path):
    from datetime import UTC, datetime, timedelta

    from horizon.model._strategy import StrategyRecord

    now = datetime(2026, 7, 9, 12, 0, 0, tzinfo=UTC)
    intake = FakeIntakePort()
    strategy = StrategyStore(tmp_path / "strategy.json")
    # a goal verified 2 days ago (on_track + done) with a live task -> should drift
    strategy.put(
        StrategyRecord(
            goal_id="g1",
            title="Old goal",
            score=0.30,
            health="on_track",
            done=True,
            task_id="task_1",
            last_outcome_at=(now - timedelta(days=2)).isoformat(),
        )
    )
    # a goal verified 5 minutes ago -> should NOT drift
    strategy.put(
        StrategyRecord(
            goal_id="g2",
            title="Fresh goal",
            score=0.30,
            health="on_track",
            done=True,
            task_id="task_2",
            last_outcome_at=(now - timedelta(minutes=5)).isoformat(),
        )
    )
    intake.priorities["task_1"] = "low"
    intake.priorities["task_2"] = "low"
    horizon = Horizon(
        goals=FakeGoalStore(),
        intake=intake,
        outcomes=FakeOutcomeFeed(),
        decisions=DecisionStore(tmp_path / "decisions.json"),
        strategy=strategy,
    )

    drifted = horizon.sweep_staleness(now=now)

    assert drifted == ["g1"]
    aged = strategy.get("g1")
    assert aged.health == "drifting"
    assert aged.done is False  # re-opened for re-verification
    assert aged.score == 0.45  # 0.30 + 0.15 stale_bump
    assert intake.priorities["task_1"] == "medium"  # 0.45 crosses the low->medium threshold
    assert strategy.get("g2").health == "on_track"  # fresh goal untouched


def test_recover_new_task_identity_survives_store_round_trip(tmp_path):
    horizon, _intake, feed = _decomposed_horizon(tmp_path)
    goal = horizon.state()[0].goals[0]
    original_task = goal.task_id

    feed.emit(
        OutcomeEvent(
            kind="run.evaluated",
            task_id=original_task,
            goal_id=goal.id,
            passed=False,
            detail="boom",
        )
    )
    recovered = horizon.recover(max_attempts=3)
    assert recovered == [goal.id]

    # A fresh read reconstructs the record from the store — the retry task must survive it.
    refreshed = next(g for g in horizon.state()[0].goals if g.id == goal.id)
    assert refreshed.task_id != original_task

    # And the retry is the goal's new root: its passing outcome completes the goal.
    feed.emit(
        OutcomeEvent(
            kind="run.evaluated",
            task_id=refreshed.task_id,
            goal_id=goal.id,
            passed=True,
        )
    )
    final = next(g for g in horizon.state()[0].goals if g.id == goal.id)
    assert final.health == "on_track"
