"""Root-authoritative outcome folding for team-shaped goals."""

# Generated by AI (UnitTest MCP)

from __future__ import annotations

from dataclasses import replace

from horizon.feedback import OutcomeFold
from horizon.model import StrategyRecord
from horizon.ports import OutcomeEvent


def _team_record() -> StrategyRecord:
    return StrategyRecord(
        goal_id="goal-1",
        root_task_id="root-1",
        task_ids=["root-1"],
        delivery_shape="team",
    )


def test_child_failure_with_active_root_drifts_goal():
    record = _team_record()

    changed = OutcomeFold().apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="child-1",
            root_task_id="root-1",
            passed=False,
        ),
    )

    assert changed is True
    assert record.health == "drifting"
    assert record.done is False
    assert record.task_outcomes == {"child-1": "failed"}
    assert record.task_ids == ["root-1", "child-1"]


def test_child_pass_without_root_verification_stays_active():
    record = _team_record()

    OutcomeFold().apply(
        record,
        OutcomeEvent(kind="run.evaluated", task_id="child-1", passed=True),
    )

    assert record.done is False
    assert record.task_outcomes["child-1"] == "passed"


def test_passing_root_subtree_outcome_completes_goal():
    record = _team_record()

    OutcomeFold().apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="root-1",
            passed=True,
            is_root_outcome=True,
        ),
    )

    assert record.done is True
    assert record.health == "on_track"
    assert record.task_outcomes["root-1"] == "passed"


def test_root_then_child_and_child_then_root_have_same_result():
    child = OutcomeEvent(kind="run.evaluated", task_id="child-1", passed=False)
    root = OutcomeEvent(
        kind="run.evaluated",
        task_id="root-1",
        passed=True,
        is_root_outcome=True,
    )
    fold = OutcomeFold()
    root_first = _team_record()
    child_first = _team_record()

    for event in (root, child):
        fold.apply(root_first, event)
    for event in (child, root):
        fold.apply(child_first, event)

    assert root_first.task_outcomes == child_first.task_outcomes
    assert (root_first.done, root_first.health) == (True, "on_track")
    assert (child_first.done, child_first.health) == (True, "on_track")


def test_duplicate_task_outcome_is_idempotent():
    record = _team_record()
    event = OutcomeEvent(kind="run.evaluated", task_id="child-1", passed=False)
    fold = OutcomeFold()
    assert fold.apply(record, event) is True
    snapshot = replace(
        record,
        task_ids=list(record.task_ids),
        task_outcomes=dict(record.task_outcomes),
    )

    assert fold.apply(record, event) is False
    assert record == snapshot


def test_blocked_required_child_blocks_goal():
    record = _team_record()

    OutcomeFold().apply(
        record,
        OutcomeEvent(kind="task.status", task_id="child-1", status="blocked"),
    )

    assert record.health == "blocked"
    assert record.done is False
    assert record.task_outcomes["child-1"] == "blocked"


def test_child_cannot_forge_root_completion_flag():
    record = _team_record()

    changed = OutcomeFold().apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="child-1",
            root_task_id="root-1",
            passed=True,
            is_root_outcome=True,
            event_id="event-child-pass",
            task_revision=1,
        ),
    )

    assert changed is True
    assert record.done is False


def test_stale_task_revision_cannot_overwrite_newer_outcome():
    record = _team_record()
    fold = OutcomeFold()
    fold.apply(
        record,
        OutcomeEvent(
            kind="task.status",
            task_id="child-1",
            status="blocked",
            event_id="event-new",
            task_revision=2,
        ),
    )
    snapshot = replace(
        record,
        task_ids=list(record.task_ids),
        task_outcomes=dict(record.task_outcomes),
        task_outcome_revisions=dict(record.task_outcome_revisions),
        outcome_event_ids=list(record.outcome_event_ids),
    )

    changed = fold.apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="child-1",
            passed=True,
            event_id="event-old",
            task_revision=1,
        ),
    )

    assert changed is False
    assert record == snapshot


def test_exact_event_replay_is_ignored_even_when_payload_conflicts():
    record = _team_record()
    fold = OutcomeFold()
    fold.apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="child-1",
            passed=False,
            event_id="event-1",
            task_revision=1,
        ),
    )

    changed = fold.apply(
        record,
        OutcomeEvent(
            kind="run.evaluated",
            task_id="child-1",
            passed=True,
            event_id="event-1",
            task_revision=2,
        ),
    )

    assert changed is False
    assert record.task_outcomes["child-1"] == "failed"